# Generated by Django 2.0.5 on 2018-08-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basecart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(1, 'Electronics'), (2, 'Fasion'), (3, 'Home'), (4, 'Toys'), (5, 'Books')], default=1),
        ),
    ]
